baseURL: https://papercupconstruction.com/
languageCode: en-us
title: Paper Cup Construction

Params:
  subtitle: A surprising and stimulating activity

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Gallery
      url: /gallery
      weight: 2
    - name: Book
      url: /book
      weight: 3
    - name: About
      url: /about
      weight: 4
    - name: Contact
      url: /contact
      weight: 5
